Repository konveyor/move2kube-ui, pull requests merged in 2020-12, with the labels that each got.

#33 fix: release workflow to match the cli release workflow
  .github/workflows/assignproject.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
Labels: bug

#35 fix: reformat workflow files
  .github/workflows/assignproject.yml
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
Labels: bug

#36 fix: Show the hint and the default value
  src/app/QA/Confirm.tsx
  src/app/QA/Input.tsx
  src/app/QA/MultiSelect.tsx
  src/app/QA/Multiline.tsx
  src/app/QA/Password.tsx
  src/app/QA/Select.tsx
Labels: bug

#38 feat: label pull requests based on their title
  .github/workflows/labelpr.yml
Labels: enhancement

#40 fix: QA bug and display default value for Input type
  src/app/QA/Input.tsx
  src/app/QA/Multiline.tsx
Labels: fix

#41 fix: QA bug in Password type
  src/app/QA/Password.tsx
Labels: fix

#42 fix: Define service start order
  docker-compose.yml
Labels: fix

#43 fix: QA bug in Confirm type
  src/app/QA/Confirm.tsx
Labels: fix

#46 fix: Update the Move2Kube command line tool download url
  src/app/Application/ApplicationAssets.tsx
Labels: fix

#50 fix: Change default dir to workspace
  .dockerignore
  .gitignore
  docker-compose.yml
Labels: fix

#53 ci: clean up workflows to work together across multiple repos
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
  Makefile
Labels: ci

#54 fix: Optimize container image size and use fedora as base image
  Dockerfile
  Dockerfile.aio
Labels: fix

#55 fix: Change support link to point to website
  Dockerfile.aio
  src/app/Support/Support.tsx
Labels: fix

#56 feat: Add support for move2kube debug mode
  package.json
  src/app/Application/Application.tsx
  src/app/Application/ApplicationPlan.tsx
  src/app/Applications/Applications.tsx
  src/app/QA/Wizard.tsx
Labels: feat

#57 fix: Change notification message on image build
  .github/workflows/build.yml
  Dockerfile.aio
Labels: fix

#58 ci: fix bug where the 2 args were being treated as a single arg and passed to GREN
  .github/workflows/release.yml
Labels: ci

#59 ci: see https://github.com/konveyor/move2kube/pull/371 for details
  .github/workflows/release.yml
Labels: ci
