Repository konveyor/move2kube-ui, pull requests merged in 2021-07, with the labels that each got.

#87 fix: progress events for upload are fired on xhr.upload, progress events for download are fired on xhr
  src/app/Application/ApplicationAssets.tsx
Labels: fix

#88 feat: support move2kube v0.3
  src/app/Application/Application.tsx
  src/app/Application/ApplicationArtifacts.tsx
  src/app/Application/ApplicationAssets.tsx
  src/app/Application/ApplicationPlan.tsx
  src/app/Application/GuidedFlow.tsx
  src/app/Application/Types.ts
  src/app/Applications/Applications.tsx
Labels: feat

#89 fix: plan not displaying properly in the plan tab outside of guided flow
  src/app/Application/Application.tsx
  src/app/Application/ApplicationPlan.tsx
  src/app/Application/GuidedFlow.tsx
  src/app/Application/Types.ts
  src/app/Networking/api.ts
Labels: fix

#90 refactor: Change base image to ubi8
  .dockerignore
  Dockerfile
  Dockerfile.aio
  Dockerfile.dev
Labels: refactor

#91 feat: allow uploading the customization directory
  src/app/Application/Application.tsx
  src/app/Application/ApplicationArtifacts.tsx
  src/app/Application/ApplicationAssets.tsx
  src/app/Application/ApplicationPlan.tsx
  src/app/Application/GuidedFlow.tsx
  src/app/Application/Types.ts
  src/app/Networking/api.ts
  src/app/app.css
Labels: feat
