Repository konveyor/move2kube-ui, pull requests merged in 2021-02, with the labels that each got.

#62 feat: Send problem obj as solution
  src/app/QA/Confirm.tsx
  src/app/QA/Input.tsx
  src/app/QA/MultiSelect.tsx
  src/app/QA/Multiline.tsx
  src/app/QA/Password.tsx
  src/app/QA/Select.tsx
  src/app/QA/Wizard.tsx
Labels: feat

#65 fix: replace gren with custom action because gren doesn't handle previous tag properly
  .github/workflows/release.yml
  .grenrc.js
Labels: fix

#66 chore: previous tag is required to calculate changelog
  .github/workflows/release.yml
Labels: chore
