Repository konveyor/move2kube-ui, pull requests merged in 2021-09, with the labels that each got.

#96 chore: update readme with new commands
  README.md
Labels: chore

#99 fix: set default shell to bash for consistency
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
Labels: fix

#98 feat: Use docker or podman to build and run the UI
  Makefile
  README.md
Labels: feat

#100 fix: update patternfly to correct styles for hidden divs. Also change download filename to be shorter and normalized
  package.json
  src/app/projects/ProjectOutputs.tsx
  yarn.lock
Labels: fix

#101 feat: open the qa wizard after clicking start transformation
  src/app/projects/ProjectOutputs.tsx
Labels: feat
