Repository konveyor/move2kube-ui, pull requests merged in 2022-07, with the labels that each got.

#121 feat: support multi arch image build
  .github/workflows/build.yml
  .github/workflows/release.yml
  Makefile
  package.json
  webpack.common.js
  yarn.lock
Labels: feat

#122 chore: move to pnpm as the package manager
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.0.0.cjs
  .yarn/releases/yarn-3.0.2.cjs
  .yarnrc.yml
  Dockerfile
  Makefile
  package.json
  pnpm-lock.yaml
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: chore

#123 fix: have webpack ignore unnecessary files and folders, remove unused packages and imports, update packages
  .eslintrc.js
  helm-charts/move2kube/templates/move2kube-api-stateful-set.yaml
  package.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/app/common/AppContextProvider.tsx
  src/app/common/ApplicationContext.tsx
  src/app/common/utils.ts
  src/app/layout/AppLayout.tsx
  src/app/login/Login.tsx
  src/app/networking/api.ts
  src/app/networking/login.ts
  src/app/not-found/NotFound.tsx
  src/app/projects/NewProjectForm.tsx
  src/app/projects/Project.tsx
  src/app/projects/ProjectInputs.tsx
  src/app/projects/ProjectOutputGraph.tsx
  src/app/projects/ProjectOutputs.tsx
  src/app/projects/ProjectPlan.tsx
  src/app/projects/Projects.tsx
  src/app/qa/Confirm.tsx
  src/app/qa/Hints.tsx
  src/app/qa/Input.tsx
  src/app/qa/MultiSelect.tsx
  src/app/qa/Multiline.tsx
  src/app/qa/Password.tsx
  src/app/qa/QAContext.tsx
  src/app/qa/QAWizard.tsx
  src/app/qa/Select.tsx
  src/app/routes/AppRoutes.tsx
  src/app/routes/DynamicImport.tsx
  src/app/support/Support.tsx
  src/app/workspaces/NewWorkspaceForm.tsx
  src/app/workspaces/Workspace.tsx
  src/app/workspaces/WorkspaceInputs.tsx
  src/app/workspaces/Workspaces.tsx
  src/custom.d.ts
  src/index.tsx
  tsconfig.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: fix

#124 fix: enable corepack before trying to build in the workflows
  .github/workflows/build.yml
  .github/workflows/release.yml
  helm-charts/move2kube/templates/move2kube-api-stateful-set.yaml
  helm-charts/move2kube/values.yaml
Labels: fix

#125 fix: HOSTNAME was not being filled in properly.
  .npmrc
  README.md
  helm-charts/move2kube/templates/auth-server-service.yaml
  helm-charts/move2kube/templates/database-service.yaml
  helm-charts/move2kube/templates/move2kube-api-stateful-set.yaml
  package.json
  pnpm-lock.yaml
  src/app/common/utils.ts
  src/app/layout/AppLayout.tsx
  src/app/projects/ProjectPlan.tsx
  src/app/qa/QAWizard.tsx
  src/app/routes/DynamicImport.tsx
  src/app/support/Support.tsx
Labels: fix

#126 fix: add back the favicon and fix type
  README.md
  webpack.common.js
Labels: fix
